GET http://localhost:3600/users

###
GET http://localhost:3600/users/5e7e7e8011067040a0d2c702
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZTdlOTNlYTExMDY3MDQwYTBkMmM3MDgiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBlcm1pc3Npb25MZXZlbCI6MSwicHJvdmlkZXIiOiJlbWFpbCIsIm5hbWUiOiJGaXJzdDIzMzMzIExhc3QyIiwicmVmcmVzaEtleSI6IndwWDU1bFBGK1AwUlJyVjBsZDlOanc9PSIsImlhdCI6MTU4NTM1NjQ5M30.pS1vNMhnSibNEg1Zn25I7dLtVPx2ehDMJ0ptm7eK1Rc

###

GET https://dropent-backend.herokuapp.com/users/

//ObjectId("5e7ea2add6db6f57efd5a1bf")

    //name: String,
    //owner: { type: Schema.ObjectId, ref: "Users", required: true },
    //ownedTrees: [{ type: Schema.ObjectId, ref: "Trees" }],
   // points: Number
//

###
GET http://localhost:3600/gardens

###

POST http://localhost:3600/gardens
Content-Type: application/json

{
    "name": "Admin Garden",
    "owner": "5e7fe4319e36c9001788075b",
    "ownedTrees": ["5e7fa803187384425bfec3b5","5e7fa803187384425bfec3b6", "5e7fa803187384425bfec3b5"],
    "points": 1234
}


//    name: String,
//    type: Number,
//   level: Number,
//   points: Number
###
POST http://localhost:3600/trees
Content-Type: application/json

{
    "name": "Fourth",
    "type": 4,
    "level": 12,
    "points": 299,
    "x": 10,
    "y": 5
}

###

GET http://localhost:3600/trees


###
POST https://dropent-backend.herokuapp.com/users
Content-Type: application/json

{
    "firstName": "First233",
    "lastName": "Last233",
    "email": "email@ndke.com",
    "password": "dasdsad333"
}





###

DELETE http://localhost:3600/gardens/5e7fb1c9b55e0949fbd5565a

###

PATCH http://localhost:3600/gardens/5e7fbab333b07151fb20659e
Content-Type: application/json

{
    "ownedTrees": ["5e7f94378b626e31cd287aad","5e7f94378b626e31cd287aad","5e7f94378b626e31cd287aa3"]
}


###

DELETE http://localhost:3000/users/5e7d60fdee6453212d21e81b

###

PATCH http://localhost:3000/users/5e7d60fdee6453212d21e81b
Content-Type: application/json

{
    "firstName": "First233",
    "lastName": "Last233",
    "email": "email33@ndke.com",
    "password": "dasdsad333"
}
